# Site settings
title: Tristan's Blog
description: Building awesome things in .net
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.tristan-rhodes.co.uk"
paginate: 5
paginate_path: "/page:num/"

authors:
  tristan-rhodes:
    name: Tristan Rhodes
    avatar: /images/avatars/tristan-rhodes.jpg

# Build settings
highlighter: rouge
markdown: kramdown
permalink: pretty
permalink: /:title.html
exclude: [
    'README.md',
    'Gemfile',
    'Gemfile.lock',
    'deploy.ps1',
    'vendor',
    'Rakefile'
]
gems:
  - jekyll-sitemap
  - jekyll-paginate